# Generated by Django 6.1.1 on 2026-09-04 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arenas', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Practice Quiz Attempt', max_length=255)),
                ('question_filter', models.CharField(choices=[('ALL', 'All Question Types'), ('MCQ', 'Multiple Choice Only'), ('SHORT', 'Short Answer Only'), ('LONG', 'Long Answer Only')], default='ALL', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_mcq_count', models.IntegerField(default=0)),
                ('correct_mcq_count', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='arenas.arena')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('self_rating', models.IntegerField(blank=True, help_text='User self-score (1-5) for subjective questions', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
            ],
            options={
                'ordering': ['question__created_at'],
            },
        ),
    ]
