# Generated by Django 6.1.1 on 2026-09-04 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the Arena / Notebook', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description or topic summary')),
                ('color_theme', models.CharField(choices=[('indigo', 'Indigo'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose'), ('sky', 'Sky'), ('violet', 'Violet'), ('teal', 'Teal')], default='indigo', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='arena_documents/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('page_count', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Extraction'), ('PROCESSING', 'Extracting Text & Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='arenas.arena')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
