# Generated by Django 6.1.1 on 2026-09-04 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arenas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'In Progress'), ('SUCCESS', 'Completed'), ('FAILURE', 'Failed')], default='PENDING', max_length=20)),
                ('total_requested', models.IntegerField(default=0)),
                ('generated_count', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='arenas.arena')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='arenas.arena')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='arenas.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
