# Generated by Django 6.1.1 on 2026-09-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='distractor_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Why each incorrect option is invalid'),
        ),
        migrations.AddField(
            model_name='question',
            name='grounding_evidence',
            field=models.TextField(blank=True, help_text='Direct quote/fact from source document proving the answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiagent_verified',
            field=models.BooleanField(default=False, help_text='Passed 4-agent consensus verification'),
        ),
        migrations.AddField(
            model_name='question',
            name='step_by_step_reasoning',
            field=models.TextField(blank=True, help_text='Detailed deductive reasoning leading to the answer'),
        ),
    ]
