import uuid
from django.db import models


class Question(models.Model):
    """
    An individual question generated by AI from PDF context.
    Supports Multiple Choice, Short Answer, and Long/Descriptive questions.
    """
    TYPE_CHOICES = [
        ('MCQ', 'Multiple Choice'),
        ('SHORT', 'Short Answer'),
        ('LONG', 'Long Answer'),
    ]

    DIFFICULTY_CHOICES = [
        ('EASY', 'Easy'),
        ('MEDIUM', 'Medium'),
        ('HARD', 'Hard'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    arena = models.ForeignKey('arenas.Arena', on_delete=models.CASCADE, related_name='questions')
    document = models.ForeignKey('arenas.Document', on_delete=models.SET_NULL, null=True, blank=True, related_name='questions')
    question_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='MEDIUM')
    question_text = models.TextField()
    
    # For MCQ: list of 4 options (e.g. ["A) Paris", "B) London", ...])
    options = models.JSONField(default=list, blank=True)
    
    # Correct option for MCQ, or ideal model answer for Short/Long
    correct_answer = models.TextField()
    
    # Explanation / rationale / pedagogical context
    explanation = models.TextField(blank=True)
    
    # Key points / keywords / grading criteria for short/long answers
    key_points = models.JSONField(default=list, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"[{self.question_type}] {self.question_text[:60]}..."

    @property
    def is_mcq(self) -> bool:
        return self.question_type == 'MCQ'

    @property
    def is_short(self) -> bool:
        return self.question_type == 'SHORT'

    @property
    def is_long(self) -> bool:
        return self.question_type == 'LONG'


class GenerationTask(models.Model):
    """
    Tracks Celery background generation tasks for an Arena.
    Allows polling for real-time progress in the UI.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('STARTED', 'In Progress'),
        ('SUCCESS', 'Completed'),
        ('FAILURE', 'Failed'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task_id = models.CharField(max_length=255, unique=True)
    arena = models.ForeignKey('arenas.Arena', on_delete=models.CASCADE, related_name='generation_tasks')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    total_requested = models.IntegerField(default=0)
    generated_count = models.IntegerField(default=0)
    message = models.CharField(max_length=255, blank=True)
    error_detail = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Task {self.task_id[:8]} - {self.status} ({self.arena.name})"

